import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:prof_design_app/src/widgets/tomb_button.dart';

final tombButtons = <TombButton>[
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.carBurst,
    name: 'Motor Accident',
    color1: const Color(0xff6989F5),
    color2: const Color(0xff906EF5),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.plus,
    name: 'Medical Emergency',
    color1: const Color(0xff66A9F2),
    color2: const Color(0xff536CF6),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.masksTheater,
    name: 'Theft / Harrasement',
    color1: const Color(0xffF2D572),
    color2: const Color(0xffE06AA3),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.personBiking,
    name: 'Awards',
    color1: const Color(0xff317183),
    color2: const Color(0xff46997D),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.carBurst,
    name: 'Motor Accident',
    color1: const Color(0xff6989F5),
    color2: const Color(0xff906EF5),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.plus,
    name: 'Medical Emergency',
    color1: const Color(0xff66A9F2),
    color2: const Color(0xff536CF6),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.masksTheater,
    name: 'Theft / Harrasement',
    color1: const Color(0xffF2D572),
    color2: const Color(0xffE06AA3),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.personBiking,
    name: 'Awards',
    color1: const Color(0xff317183),
    color2: const Color(0xff46997D),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.carBurst,
    name: 'Motor Accident',
    color1: const Color(0xff6989F5),
    color2: const Color(0xff906EF5),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.plus,
    name: 'Medical Emergency',
    color1: const Color(0xff66A9F2),
    color2: const Color(0xff536CF6),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.masksTheater,
    name: 'Theft / Harrasement',
    color1: const Color(0xffF2D572),
    color2: const Color(0xffE06AA3),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.personBiking,
    name: 'Awards',
    color1: const Color(0xff317183),
    color2: const Color(0xff46997D),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.carBurst,
    name: 'Motor Accident',
    color1: const Color(0xff6989F5),
    color2: const Color(0xff906EF5),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.plus,
    name: 'Medical Emergency',
    color1: const Color(0xff66A9F2),
    color2: const Color(0xff536CF6),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.masksTheater,
    name: 'Theft / Harrasement',
    color1: const Color(0xffF2D572),
    color2: const Color(0xffE06AA3),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.personBiking,
    name: 'Awards',
    color1: const Color(0xff317183),
    color2: const Color(0xff46997D),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.carBurst,
    name: 'Motor Accident',
    color1: const Color(0xff6989F5),
    color2: const Color(0xff906EF5),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.plus,
    name: 'Medical Emergency',
    color1: const Color(0xff66A9F2),
    color2: const Color(0xff536CF6),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.masksTheater,
    name: 'Theft / Harrasement',
    color1: const Color(0xffF2D572),
    color2: const Color(0xffE06AA3),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.personBiking,
    name: 'Awards',
    color1: const Color(0xff317183),
    color2: const Color(0xff46997D),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.carBurst,
    name: 'Motor Accident',
    color1: const Color(0xff6989F5),
    color2: const Color(0xff906EF5),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.plus,
    name: 'Medical Emergency',
    color1: const Color(0xff66A9F2),
    color2: const Color(0xff536CF6),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.masksTheater,
    name: 'Theft / Harrasement',
    color1: const Color(0xffF2D572),
    color2: const Color(0xffE06AA3),
  ),
  TombButton(
    onPress: () {},
    icon: FontAwesomeIcons.personBiking,
    name: 'Awards',
    color1: const Color(0xff317183),
    color2: const Color(0xff46997D),
  ),
];
